language: c
compiler: gcc
services:
- docker
before_script:
  - mkdir -p "$HOME/.nerves/dl"
  - cp -r vendor/* "$HOME/.nerves/dl"
script: make docker
cache:
  directories:
  - "$HOME/.nerves/dl"
before_deploy:
- cd dist
deploy:
  skip_cleanup: true
  provider: s3
  region: us-west-1
  access_key_id: AKIAJHCM4JILUOCKQFXA
  secret_access_key:
    secure: uZZQYRpV1ZfRGqbokr4fNBDi5jD+kXG7bO19dcXuzEqCIjONCG1fA+j+bPlj+MIAIAwdlc5v8PP88KLpU/f/Hz7MX9b50NVheF+6LL+g0sKJRAn/1QpaZBXtCqGK4rfzIM8rO0Nl1dQ4cHqYAFJ3Q3BbMZ9apyxb4+Pgxa5mFFhPPlk2Z6YRF79bGojNWvbMFZlL3RDso7DsLR5TwxJBJn4pudCUDWpfT5tKqrZYr2RcVvV7lgQqimY+0IMp9j3LHNmtvTyXuFupLVygBIHwY8woiZQ4j9I3MNAW4k+7teCFlftnh25eNmIZCWUH6rtj1wJq1PFUPiPpqNIO/Grz9F5RUDJ2DBvvO0eWeB1NjvnKFdWeiLxgp1ukxsrxbMSudPSjyFHjfEPbs+ub75lsDJCKqDQlIfeybPx+nI0cWcZeLLfl2R4bxWUM7yDSEiJa0LoUr5xz82jtmMBMxx61B/o6EEEAPxp+Afw0LtkqI6eum1djnpDkanq7OMYlusr3GXWEgKpoO7fZ42ktlt6RzGidoOMsGxN7VXVh77qCYBXUi97WMlAnncIgI1gGZODM0sMqlyFTvFDuK1VXQnAjm4ZQqGnPbKjRM4J76XJ+OBsGGxBsrsRkT6dwatJYvGwr9GEFzGJVNwqitu52RpDivGZ5mnQ2fPt44D0sh8gMdMM=
  bucket: ly-archive.iotcloud.io
  acl: public_read
  on:
    repo: bcdevices/ly10-system-rpi3
    all_branches: true
notifications:
  slack:
    secure: rLO0GQsAaXrIdJ4u2vJBoNDw5na7ijNRjEkeeR1QaYQWHeO8XqVu9SmCddXgaU2cyyoEjXgLsg4CBaTuNzhMO0RBg1k3eLK7/1zr6DGZZvi7p3GviqqNoWdKoieA+z/rDs0fwUFUeG6PfOq3c8g8vTjRhm4qmep9ZzMPyPhHZMlJbzqt8hUbFIKV2AXFclqpdgKObR4l+0Oc/9bXQYi4Rm20nUfQrwAFoyhE4t+18QMbAbiat3ZrkfMM+dIu1OJL23W6DjU8kQe8ewCDlpgyfwH9l9z49an1oxfx6phJVfM1/jQhRe9S1pIKrwzeLXQ6qkOapN4IkcJWRSC1sXjWyMlgcycDnA4u1vomJZ1aO8PWT/kMVnCEaJbCsWY86Avody97kmdC6ayxega26oBaXntNN+2C7Z07l3/DbHzqNCO7ts+s+gTseKk7zDo84jh+rIauGHy/7S2HCLtOKyTUOOnw3ZajzWGM/qhsYtvw/EyjaTPYN+JETQ0jHGsVhs0aI+e3NdhY+CR4Y91tWC/VUWgfmYPV0fr7ie7Pstz21QSwMCfM0d96PDVUKD7+CUg/2uZ6XRB+zYpZzMefvj8t6VsDL8cGtRKxxeitPzm2eQK8wHQwmqNY4RF2+Dw32/oUXU5uEFVegBkmkwbXraQwrAT8j95obCPmW4qgsk3EJ6A=
